### PR TITLE
Scala 2.11

### PR DESCRIPTION
**Pull request by agustafson**
Cross-build with scala 2.11
Upgrade akka 2.3.0 -> 2.3.9, scalatest 2.0 -> 2.2.4
Fix for issue #6

### CODE REVIEW

**Comment by kerryjj** [comment]
+1

**Comment by agustafson** [comment]
any chance we might be able to get this merged sometime please? ta :)

**Comment by theon** [comment]
Thanks! I'll get a new release published.

**Comment by theon** [comment]
Thanks again for the contribution! This is now released as `0.0.5`.

**Comment by agustafson** [comment]
fantastic! thanks @theon

**Pull request merged**
